version: "3"

services:

    db:
        image: mysql:5.7
        restart: always
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: welc0me
        networks:
            - back

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: welc0me
        networks:
            - back

networks:
    back:

volumes:
    db_data:
